{"name": "test_ba", "status": "failed", "statusDetails": {"message": "AssertionError: assert 3 == 4", "trace": "def test_ba():\n        a = 3\n        b = 4\n>       assert a == b\nE       assert 3 == 4\n\nInheri_test.py:8: AssertionError"}, "start": 1650035023122, "stop": 1650035023123, "uuid": "3508d1b7-b064-4adf-a6a4-74e298a6c804", "historyId": "83dee67e088a487fbb093152de4453b9", "testCaseId": "2bfb25c37d47f19eb3220ff0aa0663da", "fullName": "Inheri_test#test_ba", "labels": [{"name": "suite", "value": "Inheri_test"}, {"name": "host", "value": "MSDT120"}, {"name": "thread", "value": "19292-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Inheri_test"}]}